### ISSUE TITLE
Recorder Playback: Does not play back full recording

### ISSUE THREAD

**Issue by msbense** [team5181/2016Robot#15]
The recorder can now record actions and play them back autonomously, with little to no differences in timing. 
However, the recorder seems to stop before it completes every action in the recording. Ex, if the recording is to move forward, pause, move back, pause, and move forward again, the robot will move forward, pause, and move back.

**Comment by msbense** [comment]
@frjalex Take a look at this as well

**Comment by frjalex** [comment]
Buonissimo!

Alex R-J Fang
Email:frjalex@gmail.com

2016-01-30 17:48 GMT-05:00 Mark Bense <notifications@github.com>:
