### ISSUE TITLE
Vision Processing

### ISSUE THREAD

**Issue by msbense** [team5181/2016Robot#18]
Worth looking into. 
Check [this page](https://wpilib.screenstepslive.com/s/4485/m/24194).
We have a Microsoft Lifecam HD-3000.

**Comment by frjalex** [comment]
We have made great progress in developing the codes. See #36 for more detailed descriptions.

**Comment by frjalex** [comment]
Raspberry Pi is working and actively processing images right now. See #45 and #36

**Comment by frjalex** [comment]
Now the hard part will be getting raspi to work with roborio.

**Comment by msbense** [comment]
We implemented everything we could, but ultimately decided not to rely on vision processing
