### ISSUE TITLE
Multithreading: Asynchronous acess of gamepad object throwing exceptions

### ISSUE THREAD

**Issue by msbense** [team5181/2016Robot#19]
@Connor-Devitt 

Originally, ActionBased.java and Robot.java had their own gamepad objects, each initialized to port 3; The recorder would access the gamepad object and record all buttons as having a magnitude of 0 (makes sense considering no calls to getPhysicalState() were made on that object). 
    
I changed it so both classes used the same gamepad object- bad idea. Now an exception is thrown when the recorder tries to access any of the gamepad state variables while recording. I added Lock.java thinking that restricting access to the gamepad state variables would fix the issue- it didn't, exceptions are still being thrown somewhere. 

Alex and I had to leave before we could look further.

**Comment by msbense** [comment]
I think I solved this issue, check the last [pull request](https://github.com/team5181/2016Robot/pull/20).

**Comment by Connor-Devitt** [comment]
Seems like it should work.
