### ISSUE TITLE
Start documentation

### ISSUE THREAD

**Issue by frjalex** [team5181/2016Robot#23]
If we want the code to be utilizable by other teams, probably some documentation under wiki will be necessary? If possible I can complete the task.

**Comment by msbense** [comment]
Yeah, that would be great
I brought this up in issue #17 as well, 
I think we can close a few of these issues

**Comment by frjalex** [comment]
Sure. I shall start editing the wiki as soon as possible. :neckbeard:

**Comment by frjalex** [comment]
I don't think we're doing it for now.
