### ISSUE TITLE
<Sensors/RevX.java> navX failed to build

### ISSUE THREAD

**Issue by frjalex** [team5181/2016Robot#25]
Every time when the class is included, build fails. The error seems to be that it's referring to a deprecated method.<br>
Suggested troubleshooting action: include the sourcecode files in the eclipse workspace rather than downloading the preconfigured .jar file. The only way to troubleshoot the thing is only to look at the declaration.

**Comment by Connor-Devitt** [comment]
This is mostly likely due to an outdated WPILIB version. Must double check that the wpilbj is the 2016 release.

**Comment by msbense** [comment]
An outdated/incorrect WPILIB version would also explain #28

**Comment by frjalex** [comment]
Right. Shall be it

**Comment by msbense** [comment]
Fixed by updating WPILIB
