### ISSUE TITLE
Vision Processing: GRIP fails to deploy to roborio

### ISSUE THREAD

**Issue by msbense** [team5181/2016Robot#28]
It prints out some error involving networktables, and a software version mismatch

**Comment by msbense** [comment]
Fixed by updating WPILIB

**Comment by msbense** [comment]
GRIP is now failing to deploy to the roboRIO for another reason: 

```Could not verify ''ecdsa-sha2-nistp256'' host key with fingerprint ''38:74:c2:1f:0a:91:6f:d9:dd:92:78:a5:74:c1:b0:9c'' for '10.51.81.2' on port 22```
is displayed in the loading bar when trying to deploy.

**Comment by frjalex** [comment]
This is an ssh key problem. Shall be solved by adding the server's private key.

**Comment by msbense** [comment]
Coo, it's good to know you already know how to fix this.

**Comment by frjalex** [comment]
@msbense Actually I'm little confused. Shouldn't there also be a client side network tables?

**Comment by frjalex** [comment]
Otherwise why shouldn't you use local command execution?

**Comment by frjalex** [comment]
I see. NetworkTables is totally unecessary

**Comment by msbense** [comment]
I'm not really sure what you're talking about :confused:. Are you still talking about the first error? Because that's no longer the issue

**Comment by frjalex** [comment]
Oh no. I see now. I'm just analyzing the codes

**Comment by msbense** [comment]
Fixed by updating to latest version of GRIP (v1.2.0).
