### ISSUE TITLE
RPI + RoboRio Design

### ISSUE THREAD

**Issue by frjalex** [team5181/2016Robot#36]
We'll have to figure out how to actually coorporate between Raspberry Pi and RoboRIo. So initially I thought we can connect robo to rpi using a usb-c cable, which will be faster than ethernet.

**Comment by frjalex** [comment]
We already got camera working.

**Comment by frjalex** [comment]
It appears that either Raspberry Pi 1 is too slow or something is wrong with GRIP network stack, when communicating with an IP camera. See #37

**Comment by frjalex** [comment]
#37

**Comment by frjalex** [comment]
See #39 . Now we're almost successful getting GRIP to work with RPI. Just need to figure out #38 and how to communicate with RoboRio.

**Comment by frjalex** [comment]
#39 is fixed.

**Comment by frjalex** [comment]
It brought us the new issue of #45 though.

**Comment by frjalex** [comment]
#42 's proposed network stack tuning has been tried, but no use.

**Comment by frjalex** [comment]
Solved #45 . Vision processing on Pi is working now.
<br>
All we need to do is to hook Raspberry Pi onto Roborio now.

**Comment by frjalex** [comment]
We changed the GRIP+RPI Design to Middle layer+OpenCV + Raspberry Pi. It will be discussed in a different repository.

**Comment by msbense** [comment]
This is just about finished, and belongs on another repository anyway
