### ISSUE TITLE
Testing for TCP Codes

### ISSUE THREAD

**Issue by frjalex** [team5181/2016Robot#41]
Connor and I added the TCP server and client under pacakges <code>in.derros.netfang.tcp.server</code> and <code>in.derros.netfang.tcp.client</code>. The code is building right now, but proper testing shall still be conducted.

**Comment by frjalex** [comment]
Code still not working. see #44

**Comment by Connor-Devitt** [comment]
Yesterday I wrote a simple asynchronous server/client model but for some reason it wasn't added with the other push. With a minute of work the two new files should be able to replace the other model and should work in the intended way

**Comment by frjalex** [comment]
Note that the server + cli is being seperated to the pi/ repository.

**Comment by msbense** [comment]
Check the last few commits to team5181/pi
