### ISSUE TITLE
Cant' bear the bear not working. Bear it right next time!

### ISSUE THREAD

**Issue by frjalex** [team5181/2016Robot#43]
The team bear is not functioning in codes! Must get the bear awake next time! :bear:

**Comment by frjalex** [comment]
See 839c97ad3d5f2b643be329718cd6e6e52f201e25

**Comment by Connor-Devitt** [comment]
Can't bear the bear because it has beary much memory. Must change bear to bear arrayList. Heap has more memory and should bear the bear.

**Comment by frjalex** [comment]
I told you, signor Devitt!

**Comment by Connor-Devitt** [comment]
Beary well. We'll bear it later

**Comment by frjalex** [comment]
Looks like it is related to #47

**Comment by frjalex** [comment]
Ah I don't think we'll have time to look at it within the season.

**Comment by frjalex** [comment]
Fixed.
