### ISSUE TITLE
Coordinate-based autonomous using RevX sensor

### ISSUE THREAD

**Issue by frjalex** [team5181/2016Robot#52]
Imagine the entire field as a coordinate plane. The y values are the vertical length while the x values are actually the horizontal width. The point where the robot is started is mapped by (0,0). The goal and defenses can also be mapped to their relative coordiates according to then point of origin. In this way we can locate our location on the field using a GIS-like system and therefore take according actions.

Also, since the general structure and length of the field is the same every time in each competition, this method will be generally applicable.

**Comment by Connor-Devitt** [comment]
using this system we would ha e to design a route for autonomous based in its position and abilities of the robot. If we instead integrate this method into the current autonomous we no longer have to manually route the robot.
Is there any benefit to the completely autonomous auton (so no recording) that I think you are implying?

**Comment by Connor-Devitt** [comment]
And we still have to factor in various starting positions, we will by be able to start in the snake place each match

**Comment by frjalex** [comment]
Can be closed. We've already done this part. Sorry for the tardiness of not updating github for almost >2 days.
