### ISSUE TITLE
Improvements for Westtown

### ISSUE THREAD

**Issue by Connor-Devitt** [team5181/2016Robot#53]
In order of priority:

     1. Add functionality for any additional mechanical functionality
     2. Make autonomous more robust (More defenses, easier to record, shoot ball if physically possible)
     3. ADD USELESS STUFF TO IMPRESS JUDGES (Priority: low)

**Comment by frjalex** [comment]
Impressive. Working on this now.

**Comment by frjalex** [comment]
As we finished @ westtown, I'll close this issue for now.
