### ISSUE TITLE
Autonomous implementation (For 3/23/16 (and 3/24/16))

### ISSUE THREAD

**Issue by Connor-Devitt** [team5181/2016Robot#57]
Autonomous interface should define three methods: init, setAutonState, and doAuton.
Init will replace Actionplayback and will initialized all autonomous related things (ie put the recording in a buffer)
setAutonState is called by robot.autonomous() and will stop auton if robot leaves autonomous mode
doAuton will either start the autonThread or start the main method of autonomous.

**Comment by Connor-Devitt** [comment]
init will initialized every that the constructor cannot

**Comment by frjalex** [comment]
Implemented.
